### ISSUE TITLE
convert the ADNI data to BIDS format

### ISSUE THREAD

**Issue by Wusat824** [GabrieleLozupone/AXIAL#3]
I am encountering an issue while attempting to ![file err](https://github.com/user-attachments/assets/d07597b1-cf90-4709-9996-91e2aa3f66a4) using Clinica. The command I am running is: 

clinica convert adni-to-bids -m T1 "E:\ADNI-Screening-1.5T-AD-Complete\RAW_Data" "E:\ADNI-Screening-1.5T-AD-Complete\csv" "E:\ADNI-Screening-1.5T-AD-Complete\BIDS_Directory" 

the error is 

    raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
ValueError: Empty dataset detected. Clinical data cannot be extracted.

Can you provide any suggestions on how to resolve this issue? (i try clinica 0.7.6. and version 0.8.3) but its shows same error

I would greatly appreciate any guidance or recommendations you have to help me move forward with the BIDS conversion process.

**Comment by HanBBBB** [comment]
When I ran this code, at the very end of the execution, the following result was outputted.

**Comment by HanBBBB** [comment]
When I ran this code
clinica convert adni-to-bids -m T1 E:\pycharm\AXIAL-main\dataset\ADNI1_Complete\ADNI E:\pycharm\AXIAL-main\CSV E:\pycharm\AXIAL-main\bids
 at the very end of the execution, the following result was outputted.

2024-10-14 01:28:57,742:INFO:Paths of T1 images found. Exporting images into BIDS ...
2024-10-14 01:33:39,386:INFO:Creating modality agnostic files...
2024-10-14 01:33:39,415:INFO:Creating participants.tsv...
Traceback (most recent call last):
  File "E:\Anaconda\envs\clinicaEnv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda\envs\clinicaEnv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\clinicaEnv\Scripts\clinica.exe\__main__.py", line 7, in <module>
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\clinica\cmdline.py", line 92, in main
    cli()
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\clinica\iotools\converters\adni_to_bids\adni_to_bids_cli.py", line 79, in cli
    adni_to_bids.convert_clinical_data(
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\clinica\iotools\converters\adni_to_bids\adni_to_bids.py", line 123, in convert_clinical_data
    participants_df = bids.create_participants_df(
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\clinica\iotools\bids_utils.py", line 115, in create_participants_df
    file_to_read = load_clinical_csv(
  File "E:\Anaconda\envs\clinicaEnv\lib\site-packages\clinica\iotools\converters\adni_to_bids\adni_utils.py", line 1650, in load_clinical_csv
    raise IOError(
OSError: Expecting to find exactly one file in folder E:\pycharm\AXIAL-main\CSV matching pattern APOERES(_\d{1,2}[A-Za-z]{3}\d{4})?.csv. 0 files were found instead :
[- ]

Does this result have any impact on my subsequent operations?
Based on this, when I run this code,I encountered such an error. How can I resolve it?

python data_preprocessing.py --bids_path E:\pycharm\AXIAL-main\bids --n_proc 10 --checkpoint checkpoint.txt

<img width="582" alt="1728889143409" src="https://github.com/user-attachments/assets/fb1b8287-33b5-45fb-b286-3b93576ba857">

I would greatly appreciate any guidance or suggestions you can provide, as it will help me with my next steps in research.

**Comment by zzjkh** [comment]
I also encountered some problems in the process of converting data format, due to the update of the website, I can't effectively get all the CSV table data, I really hope to get your help

**Comment by jia-huang** [comment]
it needs four csv file , but we just get one, what can i do to get else three csv file?
    # Loading needed .csv files
    adni_merge = load_clinical_csv(csv_dir, "ADNIMERGE")
    mprage_meta = load_clinical_csv(csv_dir, "MPRAGEMETA")
    mri_quality = load_clinical_csv(csv_dir, "MRIQUALITY")
    mayo_mri_qc = load_clinical_csv(csv_dir, "MAYOADIRL_MRI_IMAGEQC_12_08_15")

**Comment by jia-huang** [comment]
> I also encountered some problems in the process of converting data format, due to the update of the website, I can't effectively get all the CSV table data, I really hope to get your help

do you address this problem?
